### ISSUE TITLE
Measuring distance and bearing from within a map layer (circle, etc.)

### ISSUE THREAD

**Issue by idenchev** [gokertanrisever/leaflet-ruler#3]
Hello Goker, Thank you for the nice feature! It is very well looking and easy to use.

Perhaps my question is not an issue at all, because this could be according to ruler design. So it could be considered as recommendation.

I have my leaflet map populated with many layers - most of them are circles and semiCircles. What I need is to be able to measure when my start point is in the centre (or within) a circle marker. My problem is that when my cursor is within the area of the marker it is no longer a Cross and it gets back to its default type of pointing finger, which means that Ruler is not active and I cannot start measurement. Whenever I get out of the marker, then Cross is back.

Is there any option to keep Ruler feature active all the time until switched-off from the icon?

Thank you!

**Comment by gokertanrisever** [comment]
Hi @idenchev ,
Sorry for the late response. So if i understand you correctly, the issue is that you cannot start measuring when the cursor is inside a circle. It's true that when you hover on circle, it turns to a pointing finger. But you should still be able to measure. Can you check this link and try to measure? https://jsfiddle.net/wyehg984/7/


 If what you want is snap in the middle of the circle, its not possible now but it is a good recommendation!

**Comment by khogan02** [comment]
This works as long as there is no popup on the marker/polygon. Any guidance on how to work around that?

**Comment by khogan02** [comment]
This works except when the marker/polygon/circle/geoJSON has a popup. Any guidance on how to disable those popups when the measure tool is active?
